### ISSUE TITLE
报错////

### ISSUE THREAD

**Issue by shoushouzhuo** [yosh-matsuda/cpp-yyjson#7]
F:/wyProj2023/common/cpp_yyjson.hpp:3188:78: error: call to non-'constexpr' function 'std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::begin() [with _Tp = char; _Alloc = std::allocator<char>; std::vector<_Tp, _Alloc>::iterator = std::vector<char>::iterator]'
 3188 |             [[nodiscard]] constexpr auto begin() noexcept { return buf_.begin(); }
      |                                                                    ~~~~~~~~~~^~

**Comment by yosh-matsuda** [comment]
@shoushouzhuo Please make sure that your compiler fully supports C++20.

NG: GCC 11 https://godbolt.org/z/hKv9jznMo
OK: GCC 12 https://godbolt.org/z/TYrnc4szj
